name: demo
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.1
  sizer: ^2.0.15
  flutter_easyloading: ^3.0.5
  google_fonts: ^3.0.1
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  transparent_image: ^2.0.0
  file_picker:
  open_file: ^3.2.1
  http_parser: ^4.0.2
  convert: ^3.1.1
  video_player: ^2.4.7
  dio: ^4.0.6
  universal_io: ^2.0.4
  http: any
  image_picker_web: any
  shared_preferences: ^2.0.17


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
